// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: service_addresses.proto

package addresses

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     string                 `protobuf:"bytes,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FlatFloor     string                 `protobuf:"bytes,3,opt,name=flat_floor,json=flatFloor,proto3" json:"flat_floor,omitempty"`
	Building      string                 `protobuf:"bytes,4,opt,name=building,proto3" json:"building,omitempty"`
	Street        string                 `protobuf:"bytes,5,opt,name=street,proto3" json:"street,omitempty"`
	District      string                 `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	ZipCode       string                 `protobuf:"bytes,9,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	IsDefault     bool                   `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_service_addresses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_service_addresses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_service_addresses_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *Address) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Address) GetFlatFloor() string {
	if x != nil {
		return x.FlatFloor
	}
	return ""
}

func (x *Address) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Address) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlatFloor     string                 `protobuf:"bytes,1,opt,name=flat_floor,json=flatFloor,proto3" json:"flat_floor,omitempty"`
	Building      string                 `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	District      string                 `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	ZipCode       string                 `protobuf:"bytes,7,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	IsDefault     bool                   `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_service_addresses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_addresses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_service_addresses_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAddressRequest) GetFlatFloor() string {
	if x != nil {
		return x.FlatFloor
	}
	return ""
}

func (x *CreateAddressRequest) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *CreateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateAddressRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CreateAddressRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateAddressRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *CreateAddressRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type CreateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressResponse) Reset() {
	*x = CreateAddressResponse{}
	mi := &file_service_addresses_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressResponse) ProtoMessage() {}

func (x *CreateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_addresses_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateAddressResponse) Descriptor() ([]byte, []int) {
	return file_service_addresses_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     string                 `protobuf:"bytes,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_service_addresses_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_addresses_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_service_addresses_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAddressRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_service_addresses_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_addresses_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_service_addresses_proto_rawDescGZIP(), []int{4}
}

func (x *GetAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []*Address             `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressResponse) Reset() {
	*x = GetAddressResponse{}
	mi := &file_service_addresses_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressResponse) ProtoMessage() {}

func (x *GetAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_addresses_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressResponse.ProtoReflect.Descriptor instead.
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return file_service_addresses_proto_rawDescGZIP(), []int{5}
}

func (x *GetAddressResponse) GetAddress() []*Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type ResetDefaultAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     string                 `protobuf:"bytes,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetDefaultAddressRequest) Reset() {
	*x = ResetDefaultAddressRequest{}
	mi := &file_service_addresses_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetDefaultAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetDefaultAddressRequest) ProtoMessage() {}

func (x *ResetDefaultAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_addresses_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetDefaultAddressRequest.ProtoReflect.Descriptor instead.
func (*ResetDefaultAddressRequest) Descriptor() ([]byte, []int) {
	return file_service_addresses_proto_rawDescGZIP(), []int{6}
}

func (x *ResetDefaultAddressRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *ResetDefaultAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_service_addresses_proto protoreflect.FileDescriptor

const file_service_addresses_proto_rawDesc = "" +
	"\n" +
	"\x17service_addresses.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x02\n" +
	"\aAddress\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\tR\taddressId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"flat_floor\x18\x03 \x01(\tR\tflatFloor\x12\x1a\n" +
	"\bbuilding\x18\x04 \x01(\tR\bbuilding\x12\x16\n" +
	"\x06street\x18\x05 \x01(\tR\x06street\x12\x1a\n" +
	"\bdistrict\x18\x06 \x01(\tR\bdistrict\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x19\n" +
	"\bzip_code\x18\t \x01(\tR\azipCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\n" +
	" \x01(\bR\tisDefault\"\xf1\x01\n" +
	"\x14CreateAddressRequest\x12\x1d\n" +
	"\n" +
	"flat_floor\x18\x01 \x01(\tR\tflatFloor\x12\x1a\n" +
	"\bbuilding\x18\x02 \x01(\tR\bbuilding\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x1a\n" +
	"\bdistrict\x18\x04 \x01(\tR\bdistrict\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x19\n" +
	"\bzip_code\x18\a \x01(\tR\azipCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\">\n" +
	"\x15CreateAddressResponse\x12%\n" +
	"\aaddress\x18\x01 \x01(\v2\v.pb.AddressR\aaddress\"5\n" +
	"\x14DeleteAddressRequest\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\tR\taddressId\",\n" +
	"\x11GetAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x12GetAddressResponse\x12%\n" +
	"\aaddress\x18\x01 \x03(\v2\v.pb.AddressR\aaddress\"T\n" +
	"\x1aResetDefaultAddressRequest\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\tR\taddressId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\x8b\x03\n" +
	"\tAddresses\x12`\n" +
	"\rCreateAddress\x12\x18.pb.CreateAddressRequest\x1a\x19.pb.CreateAddressResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/address/create\x12W\n" +
	"\rDeleteAddress\x12\x18.pb.DeleteAddressRequest\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/address/del\x12Q\n" +
	"\n" +
	"GetAddress\x12\x15.pb.GetAddressRequest\x1a\x16.pb.GetAddressResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/address/get\x12p\n" +
	"\x13ResetDefaultAddress\x12\x1e.pb.ResetDefaultAddressRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/address/default/resetB\x14Z\x12Email/pb/addressesb\x06proto3"

var (
	file_service_addresses_proto_rawDescOnce sync.Once
	file_service_addresses_proto_rawDescData []byte
)

func file_service_addresses_proto_rawDescGZIP() []byte {
	file_service_addresses_proto_rawDescOnce.Do(func() {
		file_service_addresses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_addresses_proto_rawDesc), len(file_service_addresses_proto_rawDesc)))
	})
	return file_service_addresses_proto_rawDescData
}

var file_service_addresses_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_addresses_proto_goTypes = []any{
	(*Address)(nil),                    // 0: pb.Address
	(*CreateAddressRequest)(nil),       // 1: pb.CreateAddressRequest
	(*CreateAddressResponse)(nil),      // 2: pb.CreateAddressResponse
	(*DeleteAddressRequest)(nil),       // 3: pb.DeleteAddressRequest
	(*GetAddressRequest)(nil),          // 4: pb.GetAddressRequest
	(*GetAddressResponse)(nil),         // 5: pb.GetAddressResponse
	(*ResetDefaultAddressRequest)(nil), // 6: pb.ResetDefaultAddressRequest
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
}
var file_service_addresses_proto_depIdxs = []int32{
	0, // 0: pb.CreateAddressResponse.address:type_name -> pb.Address
	0, // 1: pb.GetAddressResponse.address:type_name -> pb.Address
	1, // 2: pb.Addresses.CreateAddress:input_type -> pb.CreateAddressRequest
	3, // 3: pb.Addresses.DeleteAddress:input_type -> pb.DeleteAddressRequest
	4, // 4: pb.Addresses.GetAddress:input_type -> pb.GetAddressRequest
	6, // 5: pb.Addresses.ResetDefaultAddress:input_type -> pb.ResetDefaultAddressRequest
	2, // 6: pb.Addresses.CreateAddress:output_type -> pb.CreateAddressResponse
	7, // 7: pb.Addresses.DeleteAddress:output_type -> google.protobuf.Empty
	5, // 8: pb.Addresses.GetAddress:output_type -> pb.GetAddressResponse
	7, // 9: pb.Addresses.ResetDefaultAddress:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_addresses_proto_init() }
func file_service_addresses_proto_init() {
	if File_service_addresses_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_addresses_proto_rawDesc), len(file_service_addresses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_addresses_proto_goTypes,
		DependencyIndexes: file_service_addresses_proto_depIdxs,
		MessageInfos:      file_service_addresses_proto_msgTypes,
	}.Build()
	File_service_addresses_proto = out.File
	file_service_addresses_proto_goTypes = nil
	file_service_addresses_proto_depIdxs = nil
}
