// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: service_session.proto

package session

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Session_CreateSessionId_FullMethodName = "/pb.Session/CreateSessionId"
	Session_VerifySessionId_FullMethodName = "/pb.Session/VerifySessionId"
)

// SessionClient is the client API for Session service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionClient interface {
	CreateSessionId(ctx context.Context, in *CreateSessionIdRequest, opts ...grpc.CallOption) (*CreateSessionIdResponse, error)
	VerifySessionId(ctx context.Context, in *VerifySessionIdRequest, opts ...grpc.CallOption) (*VerifySessionIdResponse, error)
}

type sessionClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionClient(cc grpc.ClientConnInterface) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) CreateSessionId(ctx context.Context, in *CreateSessionIdRequest, opts ...grpc.CallOption) (*CreateSessionIdResponse, error) {
	out := new(CreateSessionIdResponse)
	err := c.cc.Invoke(ctx, Session_CreateSessionId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) VerifySessionId(ctx context.Context, in *VerifySessionIdRequest, opts ...grpc.CallOption) (*VerifySessionIdResponse, error) {
	out := new(VerifySessionIdResponse)
	err := c.cc.Invoke(ctx, Session_VerifySessionId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServer is the server API for Session service.
// All implementations must embed UnimplementedSessionServer
// for forward compatibility
type SessionServer interface {
	CreateSessionId(context.Context, *CreateSessionIdRequest) (*CreateSessionIdResponse, error)
	VerifySessionId(context.Context, *VerifySessionIdRequest) (*VerifySessionIdResponse, error)
	mustEmbedUnimplementedSessionServer()
}

// UnimplementedSessionServer must be embedded to have forward compatible implementations.
type UnimplementedSessionServer struct {
}

func (UnimplementedSessionServer) CreateSessionId(context.Context, *CreateSessionIdRequest) (*CreateSessionIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSessionId not implemented")
}
func (UnimplementedSessionServer) VerifySessionId(context.Context, *VerifySessionIdRequest) (*VerifySessionIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySessionId not implemented")
}
func (UnimplementedSessionServer) mustEmbedUnimplementedSessionServer() {}

// UnsafeSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServer will
// result in compilation errors.
type UnsafeSessionServer interface {
	mustEmbedUnimplementedSessionServer()
}

func RegisterSessionServer(s grpc.ServiceRegistrar, srv SessionServer) {
	s.RegisterService(&Session_ServiceDesc, srv)
}

func _Session_CreateSessionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CreateSessionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_CreateSessionId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CreateSessionId(ctx, req.(*CreateSessionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_VerifySessionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySessionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).VerifySessionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_VerifySessionId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).VerifySessionId(ctx, req.(*VerifySessionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Session_ServiceDesc is the grpc.ServiceDesc for Session service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Session_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSessionId",
			Handler:    _Session_CreateSessionId_Handler,
		},
		{
			MethodName: "VerifySessionId",
			Handler:    _Session_VerifySessionId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_session.proto",
}
