// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: service_session.proto

package session

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionIdRequest) Reset() {
	*x = CreateSessionIdRequest{}
	mi := &file_service_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionIdRequest) ProtoMessage() {}

func (x *CreateSessionIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionIdRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionIdRequest) Descriptor() ([]byte, []int) {
	return file_service_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionIdRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSessionIdRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateSessionIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionIdResponse) Reset() {
	*x = CreateSessionIdResponse{}
	mi := &file_service_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionIdResponse) ProtoMessage() {}

func (x *CreateSessionIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionIdResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionIdResponse) Descriptor() ([]byte, []int) {
	return file_service_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionIdResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_service_session_proto protoreflect.FileDescriptor

const file_service_session_proto_rawDesc = "" +
	"\n" +
	"\x15service_session.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\x16CreateSessionIdRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"/\n" +
	"\x17CreateSessionIdResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2q\n" +
	"\aSession\x12f\n" +
	"\x0fCreateSessionId\x12\x1a.pb.CreateSessionIdRequest\x1a\x1b.pb.CreateSessionIdResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/session/createB\x12Z\x10Email/pb/sessionb\x06proto3"

var (
	file_service_session_proto_rawDescOnce sync.Once
	file_service_session_proto_rawDescData []byte
)

func file_service_session_proto_rawDescGZIP() []byte {
	file_service_session_proto_rawDescOnce.Do(func() {
		file_service_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_session_proto_rawDesc), len(file_service_session_proto_rawDesc)))
	})
	return file_service_session_proto_rawDescData
}

var file_service_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_session_proto_goTypes = []any{
	(*CreateSessionIdRequest)(nil),  // 0: pb.CreateSessionIdRequest
	(*CreateSessionIdResponse)(nil), // 1: pb.CreateSessionIdResponse
}
var file_service_session_proto_depIdxs = []int32{
	0, // 0: pb.Session.CreateSessionId:input_type -> pb.CreateSessionIdRequest
	1, // 1: pb.Session.CreateSessionId:output_type -> pb.CreateSessionIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_session_proto_init() }
func file_service_session_proto_init() {
	if File_service_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_session_proto_rawDesc), len(file_service_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_session_proto_goTypes,
		DependencyIndexes: file_service_session_proto_depIdxs,
		MessageInfos:      file_service_session_proto_msgTypes,
	}.Build()
	File_service_session_proto = out.File
	file_service_session_proto_goTypes = nil
	file_service_session_proto_depIdxs = nil
}
