// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: addresses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO ADDRESSES (
    USER_ID,
    ADDRESS,
    CITY,
    STATE,
    POSTAL_CODE,
    COUNTRY,
    IS_DEFAULT
) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING address_id, user_id, address, city, state, postal_code, country, is_default, created_at, updated_at
`

type CreateAddressParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Address    string      `json:"address"`
	City       pgtype.Text `json:"city"`
	State      pgtype.Text `json:"state"`
	PostalCode pgtype.Text `json:"postal_code"`
	Country    pgtype.Text `json:"country"`
	IsDefault  bool        `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Address,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM ADDRESSES
WHERE
    USER_ID = $1 AND ADDRESS_ID = $2
`

type DeleteAddressParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AddressID uuid.UUID `json:"address_id"`
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.UserID, arg.AddressID)
	return err
}

const getAddresses = `-- name: GetAddresses :many
SELECT 
    ADDRESS_ID,
    ADDRESS,
    CITY,
    STATE,
    POSTAL_CODE,
    COUNTRY,
    IS_DEFAULT
FROM 
    ADDRESSES 
WHERE 
    USER_ID = $1
`

type GetAddressesRow struct {
	AddressID  uuid.UUID   `json:"address_id"`
	Address    string      `json:"address"`
	City       pgtype.Text `json:"city"`
	State      pgtype.Text `json:"state"`
	PostalCode pgtype.Text `json:"postal_code"`
	Country    pgtype.Text `json:"country"`
	IsDefault  bool        `json:"is_default"`
}

func (q *Queries) GetAddresses(ctx context.Context, userID uuid.UUID) ([]GetAddressesRow, error) {
	rows, err := q.db.Query(ctx, getAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAddressesRow{}
	for rows.Next() {
		var i GetAddressesRow
		if err := rows.Scan(
			&i.AddressID,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDefaultAddress = `-- name: ResetDefaultAddress :one
UPDATE ADDRESSES
SET 
    IS_DEFAULT = FALSE
WHERE 
    USER_ID = $1 RETURNING address_id, user_id, address, city, state, postal_code, country, is_default, created_at, updated_at
`

func (q *Queries) ResetDefaultAddress(ctx context.Context, userID uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, resetDefaultAddress, userID)
	var i Address
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDefaultAddress = `-- name: SetDefaultAddress :one
UPDATE ADDRESSES
SET
    IS_DEFAULT = TRUE
WHERE
    USER_ID = $1 AND ADDRESS_ID = $2
    RETURNING address_id, user_id, address, city, state, postal_code, country, is_default, created_at, updated_at
`

type SetDefaultAddressParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AddressID uuid.UUID `json:"address_id"`
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, setDefaultAddress, arg.UserID, arg.AddressID)
	var i Address
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE ADDRESSES
SET
    ADDRESS = $2,
    CITY = $3,
    STATE = $4,
    POSTAL_CODE = $5,
    COUNTRY = $6,
    IS_DEFAULT = $7,
    UPDATED_AT = NOW()
WHERE
    ADDRESS_ID = $1 RETURNING address_id, user_id, address, city, state, postal_code, country, is_default, created_at, updated_at
`

type UpdateAddressParams struct {
	AddressID  uuid.UUID   `json:"address_id"`
	Address    string      `json:"address"`
	City       pgtype.Text `json:"city"`
	State      pgtype.Text `json:"state"`
	PostalCode pgtype.Text `json:"postal_code"`
	Country    pgtype.Text `json:"country"`
	IsDefault  bool        `json:"is_default"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.AddressID,
		arg.Address,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
