// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	AddressID  uuid.UUID        `json:"address_id"`
	UserID     uuid.UUID        `json:"user_id"`
	Address    string           `json:"address"`
	City       string           `json:"city"`
	State      string           `json:"state"`
	PostalCode string           `json:"postal_code"`
	Country    string           `json:"country"`
	IsDefault  bool             `json:"is_default"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	SessionID uuid.UUID        `json:"session_id"`
	Email     string           `json:"email"`
	Token     string           `json:"token"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type User struct {
	UserID       uuid.UUID        `json:"user_id"`
	FristName    string           `json:"frist_name"`
	LastName     string           `json:"last_name"`
	Email        string           `json:"email"`
	PhoneNumber  string           `json:"phone_number"`
	PasswordHash []byte           `json:"password_hash"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
