// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	AddressID  uuid.UUID        `json:"address_id"`
	UserID     uuid.UUID        `json:"user_id"`
	Address    string           `json:"address"`
	City       pgtype.Text      `json:"city"`
	State      pgtype.Text      `json:"state"`
	PostalCode pgtype.Text      `json:"postal_code"`
	Country    pgtype.Text      `json:"country"`
	IsDefault  bool             `json:"is_default"`
	CreatedAt  pgtype.TIMESTAMP(0) `json:"created_at"`
	UpdatedAt  pgtype.TIMESTAMP(0) `json:"updated_at"`
}

type Token struct {
	TokenID   uuid.UUID        `json:"token_id"`
	Email     string           `json:"email"`
	Token     pgtype.Text      `json:"token"`
	Status    string           `json:"status"`
	CreatedAt pgtype.TIMESTAMP(0) `json:"created_at"`
	ExpiresAt pgtype.TIMESTAMP(0) `json:"expires_at"`
}

type User struct {
	UserID       uuid.UUID        `json:"user_id"`
	FristName    string           `json:"frist_name"`
	LastName     string           `json:"last_name"`
	Email        string           `json:"email"`
	PhoneNumber  string           `json:"phone_number"`
	PasswordHash string           `json:"password_hash"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.TIMESTAMP(0) `json:"created_at"`
	UpdatedAt    pgtype.TIMESTAMP(0) `json:"updated_at"`
}
