// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	AddressID uuid.UUID        `json:"address_id"`
	UserID    uuid.UUID        `json:"user_id"`
	FlatFloor pgtype.Text      `json:"flat_floor"`
	Building  pgtype.Text      `json:"building"`
	Street    string           `json:"street"`
	District  string           `json:"district"`
	Region    string           `json:"region"`
	Country   string           `json:"country"`
	ZipCode   pgtype.Text      `json:"zip_code"`
	IsDefault bool             `json:"is_default"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	SessionID uuid.UUID        `json:"session_id"`
	Email     string           `json:"email"`
	Token     string           `json:"token"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type User struct {
	UserID       uuid.UUID        `json:"user_id"`
	FristName    string           `json:"frist_name"`
	LastName     string           `json:"last_name"`
	Email        string           `json:"email"`
	PhoneNumber  string           `json:"phone_number"`
	PasswordHash []byte           `json:"password_hash"`
	Role         string           `json:"role"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
