// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	GetAddressesByUserID(ctx context.Context, userID uuid.UUID) ([]Address, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ResetEmail(ctx context.Context, arg ResetEmailParams) error
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
	ResetPhoneNumber(ctx context.Context, arg ResetPhoneNumberParams) error
	SetAllAddresstoFalse(ctx context.Context, userID uuid.UUID) error
	SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) error
	UserLogin(ctx context.Context, email string) (UserLoginRow, error)
}

var _ Querier = (*Queries)(nil)
