// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	GetAddressesByUserID(ctx context.Context, userID uuid.UUID) ([]GetAddressesByUserIDRow, error)
	GetUserById(ctx context.Context, userID uuid.UUID) (GetUserByIdRow, error)
	ResetDefaultAddress(ctx context.Context, addressID uuid.UUID) (Address, error)
	ResetEmail(ctx context.Context, arg ResetEmailParams) (User, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) (User, error)
	ResetPhoneNumber(ctx context.Context, arg ResetPhoneNumberParams) (User, error)
	SetDefaultAddress(ctx context.Context, addressID uuid.UUID) (Address, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UserLogin(ctx context.Context, email string) ([]byte, error)
}

var _ Querier = (*Queries)(nil)
