// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO TOKENS (
    token_id,
    email,
    token,
    status,
    EXPIRES_AT
) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING token_id, email, token, status, created_at, expires_at
`

type CreateTokenParams struct {
	TokenID   uuid.UUID        `json:"token_id"`
	Email     string           `json:"email"`
	Token     uuid.UUID        `json:"token"`
	Status    string           `json:"status"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.TokenID,
		arg.Email,
		arg.Token,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.TokenID,
		&i.Email,
		&i.Token,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
