// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO USERS (
    FRIST_NAME,
    LAST_NAME,
    EMAIL,
    PASSWORD_HASH,
    STATUS
) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING user_id, frist_name, last_name, email, phone_number, password_hash, status, created_at, updated_at
`

type CreateUserParams struct {
	FristName    string `json:"frist_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Status       string `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FristName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FristName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserData = `-- name: GetUserData :one
SELECT
    frist_name,
    last_name,
    email,
    phone_number
FROM 
    USERS
WHERE
    user_id = $1
`

type GetUserDataRow struct {
	FristName   string `json:"frist_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
}

func (q *Queries) GetUserData(ctx context.Context, userID uuid.UUID) (GetUserDataRow, error) {
	row := q.db.QueryRow(ctx, getUserData, userID)
	var i GetUserDataRow
	err := row.Scan(
		&i.FristName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
	)
	return i, err
}

const resetEmail = `-- name: ResetEmail :one
UPDATE USERS
SET
    EMAIL = $2
WHERE
    phone_number = $1 RETURNING user_id, frist_name, last_name, email, phone_number, password_hash, status, created_at, updated_at
`

type ResetEmailParams struct {
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
}

func (q *Queries) ResetEmail(ctx context.Context, arg ResetEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, resetEmail, arg.PhoneNumber, arg.Email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FristName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetPassword = `-- name: ResetPassword :one
UPDATE USERS
SET
    PASSWORD_HASH = $2
WHERE
    EMAIL = $1 RETURNING user_id, frist_name, last_name, email, phone_number, password_hash, status, created_at, updated_at
`

type ResetPasswordParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, resetPassword, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FristName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetPhoneNumber = `-- name: ResetPhoneNumber :one
UPDATE USERS
SET
    phone_number = $2
WHERE
    EMAIL = $1 RETURNING user_id, frist_name, last_name, email, phone_number, password_hash, status, created_at, updated_at
`

type ResetPhoneNumberParams struct {
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
}

func (q *Queries) ResetPhoneNumber(ctx context.Context, arg ResetPhoneNumberParams) (User, error) {
	row := q.db.QueryRow(ctx, resetPhoneNumber, arg.Email, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FristName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userLogin = `-- name: UserLogin :one
SELECT
    PASSWORD_HASH
FROM 
    USERS
WHERE
    EMAIL = $1 LIMIT 1
`

func (q *Queries) UserLogin(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, userLogin, email)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}
