// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: service_users.proto

package users

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInformationRequest) Reset() {
	*x = UserInformationRequest{}
	mi := &file_service_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInformationRequest) ProtoMessage() {}

func (x *UserInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInformationRequest.ProtoReflect.Descriptor instead.
func (*UserInformationRequest) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{0}
}

type UserInformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FristName     string                 `protobuf:"bytes,2,opt,name=frist_name,json=fristName,proto3" json:"frist_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInformationResponse) Reset() {
	*x = UserInformationResponse{}
	mi := &file_service_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInformationResponse) ProtoMessage() {}

func (x *UserInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInformationResponse.ProtoReflect.Descriptor instead.
func (*UserInformationResponse) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserInformationResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInformationResponse) GetFristName() string {
	if x != nil {
		return x.FristName
	}
	return ""
}

func (x *UserInformationResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserInformationResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	FristName     string                 `protobuf:"bytes,2,opt,name=frist_name,json=fristName,proto3" json:"frist_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_service_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{2}
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetFristName() string {
	if x != nil {
		return x.FristName
	}
	return ""
}

func (x *SignUpRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SignUpRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FristName     string                 `protobuf:"bytes,2,opt,name=frist_name,json=fristName,proto3" json:"frist_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Msg           string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_service_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{3}
}

func (x *SignUpResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpResponse) GetFristName() string {
	if x != nil {
		return x.FristName
	}
	return ""
}

func (x *SignUpResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SignUpResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SignUpResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_service_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_service_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResetEmailAfterLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewEmail      string                 `protobuf:"bytes,1,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetEmailAfterLoginRequest) Reset() {
	*x = ResetEmailAfterLoginRequest{}
	mi := &file_service_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetEmailAfterLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEmailAfterLoginRequest) ProtoMessage() {}

func (x *ResetEmailAfterLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEmailAfterLoginRequest.ProtoReflect.Descriptor instead.
func (*ResetEmailAfterLoginRequest) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{6}
}

func (x *ResetEmailAfterLoginRequest) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

type ResetPasswordAfterLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPassword   string                 `protobuf:"bytes,1,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordAfterLoginRequest) Reset() {
	*x = ResetPasswordAfterLoginRequest{}
	mi := &file_service_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordAfterLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordAfterLoginRequest) ProtoMessage() {}

func (x *ResetPasswordAfterLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordAfterLoginRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordAfterLoginRequest) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{7}
}

func (x *ResetPasswordAfterLoginRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPhoneNumberAfterLoginRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewPhoneNumber string                 `protobuf:"bytes,1,opt,name=new_phone_number,json=newPhoneNumber,proto3" json:"new_phone_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResetPhoneNumberAfterLoginRequest) Reset() {
	*x = ResetPhoneNumberAfterLoginRequest{}
	mi := &file_service_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPhoneNumberAfterLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPhoneNumberAfterLoginRequest) ProtoMessage() {}

func (x *ResetPhoneNumberAfterLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPhoneNumberAfterLoginRequest.ProtoReflect.Descriptor instead.
func (*ResetPhoneNumberAfterLoginRequest) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{8}
}

func (x *ResetPhoneNumberAfterLoginRequest) GetNewPhoneNumber() string {
	if x != nil {
		return x.NewPhoneNumber
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_service_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_service_users_proto_rawDescGZIP(), []int{9}
}

func (x *ResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_service_users_proto protoreflect.FileDescriptor

const file_service_users_proto_rawDesc = "" +
	"\n" +
	"\x13service_users.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\x18\n" +
	"\x16UserInformationRequest\"\x8e\x01\n" +
	"\x17UserInformationResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"frist_name\x18\x02 \x01(\tR\tfristName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\"\x8a\x01\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"frist_name\x18\x02 \x01(\tR\tfristName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\"\x97\x01\n" +
	"\x0eSignUpResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"frist_name\x18\x02 \x01(\tR\tfristName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msg\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\":\n" +
	"\x1bResetEmailAfterLoginRequest\x12\x1b\n" +
	"\tnew_email\x18\x01 \x01(\tR\bnewEmail\"C\n" +
	"\x1eResetPasswordAfterLoginRequest\x12!\n" +
	"\fnew_password\x18\x01 \x01(\tR\vnewPassword\"M\n" +
	"!ResetPhoneNumberAfterLoginRequest\x12(\n" +
	"\x10new_phone_number\x18\x01 \x01(\tR\x0enewPhoneNumber\")\n" +
	"\rResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd2\x04\n" +
	"\vUserService\x12h\n" +
	"\x10UserInformations\x12\x1a.pb.UserInformationRequest\x1a\x1b.pb.UserInformationResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/users/informations\x12M\n" +
	"\n" +
	"SignUpUser\x12\x11.pb.SignUpRequest\x1a\x12.pb.SignUpResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/users/signup\x12?\n" +
	"\x05Login\x12\x10.pb.LoginRequest\x1a\x11.pb.LoginResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/login\x12c\n" +
	"\x14ResetEmailAfterLogin\x12\x1f.pb.ResetEmailAfterLoginRequest\x1a\x11.pb.ResetResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/reset-email\x12l\n" +
	"\x17ResetPasswordAfterLogin\x12\".pb.ResetPasswordAfterLoginRequest\x1a\x11.pb.ResetResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/reset-password\x12v\n" +
	"\x1aResetPhoneNumberAfterLogin\x12%.pb.ResetPhoneNumberAfterLoginRequest\x1a\x11.pb.ResetResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/reset-phone-numberB\x10Z\x0eEmail/pb/usersb\x06proto3"

var (
	file_service_users_proto_rawDescOnce sync.Once
	file_service_users_proto_rawDescData []byte
)

func file_service_users_proto_rawDescGZIP() []byte {
	file_service_users_proto_rawDescOnce.Do(func() {
		file_service_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_users_proto_rawDesc), len(file_service_users_proto_rawDesc)))
	})
	return file_service_users_proto_rawDescData
}

var file_service_users_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_users_proto_goTypes = []any{
	(*UserInformationRequest)(nil),            // 0: pb.UserInformationRequest
	(*UserInformationResponse)(nil),           // 1: pb.UserInformationResponse
	(*SignUpRequest)(nil),                     // 2: pb.SignUpRequest
	(*SignUpResponse)(nil),                    // 3: pb.SignUpResponse
	(*LoginRequest)(nil),                      // 4: pb.LoginRequest
	(*LoginResponse)(nil),                     // 5: pb.LoginResponse
	(*ResetEmailAfterLoginRequest)(nil),       // 6: pb.ResetEmailAfterLoginRequest
	(*ResetPasswordAfterLoginRequest)(nil),    // 7: pb.ResetPasswordAfterLoginRequest
	(*ResetPhoneNumberAfterLoginRequest)(nil), // 8: pb.ResetPhoneNumberAfterLoginRequest
	(*ResetResponse)(nil),                     // 9: pb.ResetResponse
}
var file_service_users_proto_depIdxs = []int32{
	0, // 0: pb.UserService.UserInformations:input_type -> pb.UserInformationRequest
	2, // 1: pb.UserService.SignUpUser:input_type -> pb.SignUpRequest
	4, // 2: pb.UserService.Login:input_type -> pb.LoginRequest
	6, // 3: pb.UserService.ResetEmailAfterLogin:input_type -> pb.ResetEmailAfterLoginRequest
	7, // 4: pb.UserService.ResetPasswordAfterLogin:input_type -> pb.ResetPasswordAfterLoginRequest
	8, // 5: pb.UserService.ResetPhoneNumberAfterLogin:input_type -> pb.ResetPhoneNumberAfterLoginRequest
	1, // 6: pb.UserService.UserInformations:output_type -> pb.UserInformationResponse
	3, // 7: pb.UserService.SignUpUser:output_type -> pb.SignUpResponse
	5, // 8: pb.UserService.Login:output_type -> pb.LoginResponse
	9, // 9: pb.UserService.ResetEmailAfterLogin:output_type -> pb.ResetResponse
	9, // 10: pb.UserService.ResetPasswordAfterLogin:output_type -> pb.ResetResponse
	9, // 11: pb.UserService.ResetPhoneNumberAfterLogin:output_type -> pb.ResetResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_users_proto_init() }
func file_service_users_proto_init() {
	if File_service_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_users_proto_rawDesc), len(file_service_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_users_proto_goTypes,
		DependencyIndexes: file_service_users_proto_depIdxs,
		MessageInfos:      file_service_users_proto_msgTypes,
	}.Build()
	File_service_users_proto = out.File
	file_service_users_proto_goTypes = nil
	file_service_users_proto_depIdxs = nil
}
